theme: minima
title: learning labs gh pages
author: Akash Gupta
email: gupta52akash@hot.mail.com
description: > # this means to ignore newlines until "baseurl:"
  Writ test e an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
